Global CONSTs
invariant-labs/protocol-alephium pull request #116
Opened 2024-07-30 10:09 UTC by DevRozaDev

+ alephium web3, stack bump
+ alephium stack update script
+ make error codes global, move to a single location (following this discussion: https://github.com/invariant-labs/protocol-alephium/pull/115#discussion_r1692791345)
+ move types to a single location alongside consts relevant to them (same discussion as above)
+ use denominator constant instead of `one` where applicable
+ replace uses of `u256Max!()` in Decimal contract with `MAX_U256`
+ display contracts' bytecode length
+ replace log getters with consts

2024-07-30 10:39 UTC, Sniezka1927 requested changes

2024-07-30 10:39 UTC, Sniezka1927 commented on contracts/invariant.ral
> +const MaxFeeTiers = 32
```suggestion
const MAX_FEE_TIERS = 32
```

2024-07-30 10:39 UTC, Sniezka1927 commented on src/math.ts
> +  if (offset >= LIQUIDITY_SCALE) throw new Error(`offset must be less than ${LIQUIDITY_SCALE}`)
We should accept offset equal to scale

2024-07-30 10:39 UTC, Sniezka1927 commented on package.json
> +    "compile": "npx cli compile && npx ts-node stats",
imo it will be better to run "npx cli compile && npm run stats", so we maintain single source of running the script

2024-07-30 11:36 UTC, Sniezka1927 commented on contracts/invariant.ral
> +const MAX_FEE_TIERS = 32
Shouldn't the const be in `constants.ral` as well as other structs moved to `structures/` directory?

2024-07-30 15:11 UTC, Sniezka1927 approved these changes

2024-07-31 04:05 UTC, wojciech-cichocki approved these changes

2024-07-31 09:04 UTC, merged