Scripts package, move the usage example there
invariant-labs/protocol-alephium pull request #122
Opened 2024-08-26 11:53 UTC by DevRozaDev

2024-08-26 12:14 UTC, Sniezka1927 requested changes

2024-08-26 12:14 UTC, Sniezka1927 commented on scripts/src/index.ts
> +  const accountToken1BalanceBeforeRemove = await token.getBalanceOf(account.address, TOKEN1_ID)
It does not look correct when we are taking id from Poolkey and from deploy result. IMO we should always suggest using poolKey. Change it in docs as well please

2024-08-26 15:36 UTC, DevRozaDev commented
Waiting on https://github.com/invariant-labs/protocol-alephium/pull/123, some of the changes there will be visible in the example.

2024-08-27 08:24 UTC, Sniezka1927 approved these changes

2024-08-27 09:11 UTC, wojciech-cichocki approved these changes

2024-08-27 09:12 UTC, merged