update alephium node and fix some warnings
invariant-labs/protocol-alephium pull request #34
Opened 2024-03-19 18:10 UTC by zielvna

2024-03-21 08:19 UTC, Sniezka1927 requested changes

2024-03-21 14:55 UTC, zielvna commented on contracts/collections/pools.ral
> +    clamm: CLAMM,
`copyCreateSubContract` only accepts `ByteVec`

2024-03-21 14:56 UTC, zielvna commented on contracts/swap.ral
> +    amountIn: U256,
not in the scope of this pr, we will change it later

2024-03-21 15:05 UTC, Sniezka1927 approved these changes

2024-03-22 07:12 UTC, wojciech-cichocki approved these changes

2024-03-22 07:55 UTC, merged