Updated get delta x & added exhausting tests
invariant-labs/protocol-alephium pull request #45
Opened 2024-04-04 09:16 UTC by Sniezka1927

2024-04-04 13:37 UTC, zielvna requested changes

2024-04-04 13:37 UTC, zielvna commented on contracts/math/clamm.ral
> +            deltaX = uints.bigDiv512(deltaX, one(SqrtPriceScale), 1)
one div will probably work there

2024-04-04 13:37 UTC, zielvna commented on contracts/math/clamm.ral
> +            let mut deltaXUp = uints.bigMul512(nominator, one(SqrtPriceScale))
i think you should use `bigMulDivUp256` here

2024-04-04 13:37 UTC, zielvna commented on test/clamm.test.ts
> +      expect(resultDown).toEqual(75884792730156830614567103553061795263351065677581979478702815696568066130225n)
test results are off

2024-04-04 14:26 UTC, zielvna approved these changes

2024-04-05 06:52 UTC, wojciech-cichocki requested changes

2024-04-05 06:52 UTC, wojciech-cichocki commented on contracts/math/clamm.ral
> +            let denominator = mul(sqrtPriceA, sqrtPriceB, SqrtPriceScale)
It seems that `U512` should be used here

2024-04-05 06:52 UTC, wojciech-cichocki commented on contracts/math/clamm.ral
> +        if (roundingUp) {
I think it's worth using abstraction here and add function that divided two numbers and return token amounts

2024-04-05 06:52 UTC, wojciech-cichocki commented on test/clamm.test.ts
> +      expect(resultUp).toEqual(3794315473971847510172532341754979462199874072217062972672351494741127621n)
What are the causes of these differences in results?

2024-04-08 16:54 UTC, wojciech-cichocki approved these changes

2024-04-09 07:41 UTC, merged