Error code checks
invariant-labs/protocol-alephium pull request #74
Opened 2024-06-24 14:18 UTC by DevRozaDev

Check for specified error codes instead of just checking whether an error occurs or not + fixes of newly discovered errors.

For `Uints` methods with `new` prefix I assumed we are trying to rely on the VM to throw `ArithmeticError` and handled it accordingly.

2024-06-24 15:34 UTC, Sniezka1927 requested changes

2024-06-24 15:34 UTC, Sniezka1927 commented on test/pools.test.ts
> +    let [tokenX, tokenY] = await initTokensXY(sender, 0n)
If the variable is not assigned anywhere else, it is better to use `const`

2024-06-24 15:34 UTC, Sniezka1927 commented on test/tickmap.test.ts
> +        args: { tick: -GlobalMaxTick + 1n, tickSpacing: 1n, poolKey }
`GlobalMinTick`, it occurs in few places inside tickmap test file

2024-06-24 15:34 UTC, Sniezka1927 commented on contracts/math/clamm.ral
> +            let denominator = uints.toU256(uints.bigMulDiv256(sqrtPriceA, sqrtPriceB, one(SqrtPriceScale)))
Do we need to extend type here?

2024-06-25 10:48 UTC, wojciech-cichocki approved these changes

2024-06-25 10:49 UTC, merged