"protocol_fee" e2e tests updated
invariant-labs/protocol-alephium pull request #76
Opened 2024-06-26 09:32 UTC by DevRozaDev

2024-06-26 09:50 UTC, Sniezka1927 commented on test/protocol_fee.test.ts
> +    )
There is missing case when fee receiver is changed and new receiver tries to withdraw protcol fee

2024-06-26 15:35 UTC, Sniezka1927 requested changes

2024-06-26 15:35 UTC, Sniezka1927 commented on src/snippets.ts
> +export const initBasicFeeTickSpacing = (): [bigint, bigint] => {
You dont initialize anything, it would be more convinient to name it `getBasicFeeTickSpacing`

2024-06-26 15:35 UTC, Sniezka1927 commented on src/snippets.ts
> +  expect(invariantBeforeExpectedBalance).toMatchObject({ tokenX: 500n, tokenY: 1000n })
Why with Expected sufix?

2024-06-26 15:35 UTC, Sniezka1927 commented on src/snippets.ts
> +  const swapperAfterExpectedBalance = {
If this is expeced balance it should be hard coded, not queried from node

2024-06-26 15:43 UTC, DevRozaDev commented on src/snippets.ts
> +  expect(invariantBeforeExpectedBalance).toMatchObject({ tokenX: 500n, tokenY: 1000n })
good catch!

2024-06-26 15:54 UTC, Sniezka1927 approved these changes

2024-06-28 05:37 UTC, wojciech-cichocki approved these changes

2024-06-28 05:38 UTC, merged