Position_list e2e tests
invariant-labs/protocol-alephium pull request #89
Opened 2024-07-03 14:39 UTC by DevRozaDev

\+ fix `positionsCounter` not decreasing when position is removed
\+ fix protocol trying to create `positionsCounter` for the caller if all his positions got removed beforehand
\+ `transferVerifyPosition`  snippet for position transferring
\+ `transferPosition` testUtil function

2024-07-03 15:46 UTC, Sniezka1927 requested changes

2024-07-03 15:46 UTC, Sniezka1927 commented on test/position_list.test.ts
> +      ].map(([i1, i2], index) => {
There is no need to map array, you can access the index and value in for loop:
```ts
const tickIndexes = [[-10n, 10n],[-20n, -10n],[10n, 20n]]
for (const [index, [lowerTick, upperTick]] of tickIndexes.entries()) {
    ...
}
```

2024-07-03 15:46 UTC, Sniezka1927 commented on test/position_list.test.ts
> +    for (let minMaxTick of minMaxTicks) {
Here you can use as well array destructuring
```ts
for (const [minIndex, maxIndex] of minMaxTick) {
    const minTick = tickIndexes[minIndex]
    const maxTick = tickIndexes[maxIndex]
    ...
}
```

2024-07-03 15:46 UTC, Sniezka1927 commented on test/position_list.test.ts
> +    {
You should check also position list length after each removal

2024-07-03 15:46 UTC, Sniezka1927 commented on src/snippets.ts
> +  sender: PrivateKeyWallet,
owner would be more clear

2024-07-03 15:46 UTC, Sniezka1927 commented on src/snippets.ts
> +  const senderFirstPositionAfter = await getPosition(invariant, sender.address, index)
It is not always first position

2024-07-04 12:17 UTC, Sniezka1927 requested changes

2024-07-04 14:38 UTC, wojciech-cichocki approved these changes

2024-07-04 14:38 UTC, wojciech-cichocki commented on src/snippets.ts
> +export const transferVerifyPosition = async (
Maybe `transferAndVerifyPosition`

2024-07-04 15:07 UTC, merged