cross_both_side e2e tests
invariant-labs/protocol-alephium pull request #92
Opened 2024-07-05 15:10 UTC by DevRozaDev

\+ support `byAmountIn` parameter in TxScript properly
\+ add `liquidity` util function

There's still an issue of how the state of one of the ticks is incorrect, despite of the global pool results being fine.

2024-07-08 17:42 UTC, Sniezka1927 requested changes

2024-07-08 17:42 UTC, Sniezka1927 commented on src/testUtils.ts
> +export const liquidity = (value: bigint) => {
The function name should be more clearer, if it applies the liquidity decimal to value maybe consider naming it `toLiquidity`.

2024-07-09 07:21 UTC, Sniezka1927 approved these changes

2024-07-09 19:05 UTC, wojciech-cichocki approved these changes

2024-07-09 19:09 UTC, merged